import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/providers/AuthProvider";
import { Toaster } from "sonner";
import NavBar from "@/components/NavBar";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${notoSans.className} antialiased`}
      >
        <AuthProvider>
        <header className="border-b">
          <NavBar />
        </header>
        <main>{children}</main>
        <Toaster richColors position="top-center" />
        </AuthProvider>
      </body>
    </html>
  );
}
